name: Terraform Pull Request
on:
  pull_request:
    branches: [ main ]

permissions: write-all

jobs:
  terraform-plan:
    uses: jtcressy-home/actions-workflows/.github/workflows/terraform.yml@main
    with:
      vault: https://vault.jtcressy.net
      tailscale: true
      action: plan
    secrets: inherit